---
name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create build directory
        shell: bash
        run: mkdir build

      - name: Setup packages
        shell: bash
        run :
          sudo apt-get install ninja-build

      - name: CMake Setup
        working-directory: build
        shell: bash
        run: |
          cmake .. -G Ninja

